/*
Navicat MySQL Data Transfer

Source Server         : LOCALHOST
Source Server Version : 50508
Source Host           : localhost:3306
Source Database       : akh

Target Server Type    : MYSQL
Target Server Version : 50508
File Encoding         : 65001

Date: 2014-05-26 16:52:34
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `master_kokab`
-- ----------------------------
DROP TABLE IF EXISTS `master_kokab`;
CREATE TABLE `master_kokab` (
  `kota_id` int(10) NOT NULL AUTO_INCREMENT,
  `kokab_nama` varchar(30) DEFAULT NULL,
  `provinsi_id` int(10) DEFAULT NULL,
  PRIMARY KEY (`kota_id`),
  KEY `pro_kota` (`provinsi_id`),
  CONSTRAINT `pro_kota` FOREIGN KEY (`provinsi_id`) REFERENCES `master_provinsi` (`provinsi_id`)
) ENGINE=InnoDB AUTO_INCREMENT=504 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of master_kokab
-- ----------------------------
INSERT INTO `master_kokab` VALUES ('1', 'Kabupaten Aceh Barat', '1');
INSERT INTO `master_kokab` VALUES ('2', 'Kabupaten Aceh Barat Daya', '1');
INSERT INTO `master_kokab` VALUES ('3', 'Kabupaten Aceh Besar', '1');
INSERT INTO `master_kokab` VALUES ('4', 'Kabupaten Aceh Jaya', '1');
INSERT INTO `master_kokab` VALUES ('5', 'Kabupaten Aceh Selatan', '1');
INSERT INTO `master_kokab` VALUES ('6', 'Kabupaten Aceh Singkil', '1');
INSERT INTO `master_kokab` VALUES ('7', 'Kabupaten Aceh Tamiang', '1');
INSERT INTO `master_kokab` VALUES ('8', 'Kabupaten Aceh Tengah', '1');
INSERT INTO `master_kokab` VALUES ('9', 'Kabupaten Aceh Tenggara', '1');
INSERT INTO `master_kokab` VALUES ('10', 'Kabupaten Aceh Timur', '1');
INSERT INTO `master_kokab` VALUES ('11', 'Kabupaten Aceh Utara', '1');
INSERT INTO `master_kokab` VALUES ('12', 'Kabupaten Bener Meriah', '1');
INSERT INTO `master_kokab` VALUES ('13', 'Kabupaten Bireuen', '1');
INSERT INTO `master_kokab` VALUES ('14', 'Kabupaten Gayo Luwes', '1');
INSERT INTO `master_kokab` VALUES ('15', 'Kabupaten Nagan Raya', '1');
INSERT INTO `master_kokab` VALUES ('16', 'Kabupaten Pidie', '1');
INSERT INTO `master_kokab` VALUES ('17', 'Kabupaten Pidie Jaya', '1');
INSERT INTO `master_kokab` VALUES ('18', 'Kabupaten Simeulue', '1');
INSERT INTO `master_kokab` VALUES ('19', 'Kota Banda Aceh', '1');
INSERT INTO `master_kokab` VALUES ('20', 'Kota Langsa', '1');
INSERT INTO `master_kokab` VALUES ('21', 'Kota Lhokseumawe', '1');
INSERT INTO `master_kokab` VALUES ('22', 'Kota Sabang', '1');
INSERT INTO `master_kokab` VALUES ('23', 'Kota Subulussalam', '1');
INSERT INTO `master_kokab` VALUES ('24', 'Kabupaten Asahan', '2');
INSERT INTO `master_kokab` VALUES ('25', 'Kabupaten Batubara', '2');
INSERT INTO `master_kokab` VALUES ('26', 'Kabupaten Dairi', '2');
INSERT INTO `master_kokab` VALUES ('27', 'Kabupaten Deli Serdang', '2');
INSERT INTO `master_kokab` VALUES ('28', 'Kabupaten Humbang Hasundutan', '2');
INSERT INTO `master_kokab` VALUES ('29', 'Kabupaten Karo', '2');
INSERT INTO `master_kokab` VALUES ('30', 'Kabupaten Labuhan Batu', '2');
INSERT INTO `master_kokab` VALUES ('31', 'Kabupaten Labuhanbatu Selatan', '2');
INSERT INTO `master_kokab` VALUES ('32', 'Kabupaten Labuhanbatu Utara', '2');
INSERT INTO `master_kokab` VALUES ('33', 'Kabupaten Langkat', '2');
INSERT INTO `master_kokab` VALUES ('34', 'Kabupaten Mandailing Natal', '2');
INSERT INTO `master_kokab` VALUES ('35', 'Kabupaten Nias', '2');
INSERT INTO `master_kokab` VALUES ('36', 'Kabupaten Nias Barat', '2');
INSERT INTO `master_kokab` VALUES ('37', 'Kabupaten Nias Selatan', '2');
INSERT INTO `master_kokab` VALUES ('38', 'Kabupaten Nias Utara', '2');
INSERT INTO `master_kokab` VALUES ('39', 'Kabupaten Padang Lawas', '2');
INSERT INTO `master_kokab` VALUES ('40', 'Kabupaten Padang Lawas Utara', '2');
INSERT INTO `master_kokab` VALUES ('41', 'Kabupaten Pakpak Barat', '2');
INSERT INTO `master_kokab` VALUES ('42', 'Kabupaten Samosir', '2');
INSERT INTO `master_kokab` VALUES ('43', 'Kabupaten Serdang Bedagai', '2');
INSERT INTO `master_kokab` VALUES ('44', 'Kabupaten Simalungun', '2');
INSERT INTO `master_kokab` VALUES ('45', 'Kabupaten Tapanuli Selatan', '2');
INSERT INTO `master_kokab` VALUES ('46', 'Kabupaten Tapanuli Tengah', '2');
INSERT INTO `master_kokab` VALUES ('47', 'Kabupaten Tapanuli Utara', '2');
INSERT INTO `master_kokab` VALUES ('48', 'Kabupaten Toba Samosir', '2');
INSERT INTO `master_kokab` VALUES ('49', 'Kota Binjai', '2');
INSERT INTO `master_kokab` VALUES ('50', 'Kota Gunung Sitoli', '2');
INSERT INTO `master_kokab` VALUES ('51', 'Kota Medan', '2');
INSERT INTO `master_kokab` VALUES ('52', 'Kota Padangsidempuan', '2');
INSERT INTO `master_kokab` VALUES ('53', 'Kota Pematang Siantar', '2');
INSERT INTO `master_kokab` VALUES ('54', 'Kota Sibolga', '2');
INSERT INTO `master_kokab` VALUES ('55', 'Kota Tanjung Balai', '2');
INSERT INTO `master_kokab` VALUES ('56', 'Kota Tebing Tinggi', '2');
INSERT INTO `master_kokab` VALUES ('57', 'Kabupaten Agam', '3');
INSERT INTO `master_kokab` VALUES ('58', 'Kabupaten Dharmas Raya', '3');
INSERT INTO `master_kokab` VALUES ('59', 'Kabupaten Kepulauan Mentawai', '3');
INSERT INTO `master_kokab` VALUES ('60', 'Kabupaten Lima Puluh Kota', '3');
INSERT INTO `master_kokab` VALUES ('61', 'Kabupaten Padang Pariaman', '3');
INSERT INTO `master_kokab` VALUES ('62', 'Kabupaten Pasaman', '3');
INSERT INTO `master_kokab` VALUES ('63', 'Kabupaten Pasaman Barat', '3');
INSERT INTO `master_kokab` VALUES ('64', 'Kabupaten Pesisir Selatan', '3');
INSERT INTO `master_kokab` VALUES ('65', 'Kabupaten Sijunjung', '3');
INSERT INTO `master_kokab` VALUES ('66', 'Kabupaten Solok', '3');
INSERT INTO `master_kokab` VALUES ('67', 'Kabupaten Solok Selatan', '3');
INSERT INTO `master_kokab` VALUES ('68', 'Kabupaten Tanah Datar', '3');
INSERT INTO `master_kokab` VALUES ('69', 'Kota Bukittinggi', '3');
INSERT INTO `master_kokab` VALUES ('70', 'Kota Padang', '3');
INSERT INTO `master_kokab` VALUES ('71', 'Kota Padang Panjang', '3');
INSERT INTO `master_kokab` VALUES ('72', 'Kota Pariaman', '3');
INSERT INTO `master_kokab` VALUES ('73', 'Kota Payakumbuh', '3');
INSERT INTO `master_kokab` VALUES ('74', 'Kota Sawah Lunto', '3');
INSERT INTO `master_kokab` VALUES ('75', 'Kota Solok', '3');
INSERT INTO `master_kokab` VALUES ('76', 'Kabupaten Bengkalis', '4');
INSERT INTO `master_kokab` VALUES ('77', 'Kabupaten Indragiri Hilir', '4');
INSERT INTO `master_kokab` VALUES ('78', 'Kabupaten Indragiri Hulu', '4');
INSERT INTO `master_kokab` VALUES ('79', 'Kabupaten Kampar', '4');
INSERT INTO `master_kokab` VALUES ('80', 'Kabupaten Kuantan Singingi', '4');
INSERT INTO `master_kokab` VALUES ('81', 'Kabupaten Meranti', '4');
INSERT INTO `master_kokab` VALUES ('82', 'Kabupaten Pelalawan', '4');
INSERT INTO `master_kokab` VALUES ('83', 'Kabupaten Rokan Hilir', '4');
INSERT INTO `master_kokab` VALUES ('84', 'Kabupaten Rokan Hulu', '4');
INSERT INTO `master_kokab` VALUES ('85', 'Kabupaten Siak', '4');
INSERT INTO `master_kokab` VALUES ('86', 'Kota Dumai', '4');
INSERT INTO `master_kokab` VALUES ('87', 'Kota Pekanbaru', '4');
INSERT INTO `master_kokab` VALUES ('88', 'Kabupaten Bintan', '5');
INSERT INTO `master_kokab` VALUES ('89', 'Kabupaten Karimun', '5');
INSERT INTO `master_kokab` VALUES ('90', 'Kabupaten Kepulauan Anambas', '5');
INSERT INTO `master_kokab` VALUES ('91', 'Kabupaten Lingga', '5');
INSERT INTO `master_kokab` VALUES ('92', 'Kabupaten Natuna', '5');
INSERT INTO `master_kokab` VALUES ('93', 'Kota Batam', '5');
INSERT INTO `master_kokab` VALUES ('94', 'Kota Tanjung Pinang', '5');
INSERT INTO `master_kokab` VALUES ('95', 'Kabupaten Bangka', '6');
INSERT INTO `master_kokab` VALUES ('96', 'Kabupaten Bangka Barat', '6');
INSERT INTO `master_kokab` VALUES ('97', 'Kabupaten Bangka Selatan', '6');
INSERT INTO `master_kokab` VALUES ('98', 'Kabupaten Bangka Tengah', '6');
INSERT INTO `master_kokab` VALUES ('99', 'Kabupaten Belitung', '6');
INSERT INTO `master_kokab` VALUES ('100', 'Kabupaten Belitung Timur', '6');
INSERT INTO `master_kokab` VALUES ('101', 'Kota Pangkal Pinang', '6');
INSERT INTO `master_kokab` VALUES ('102', 'Kabupaten Kerinci', '7');
INSERT INTO `master_kokab` VALUES ('103', 'Kabupaten Merangin', '7');
INSERT INTO `master_kokab` VALUES ('104', 'Kabupaten Sarolangun', '7');
INSERT INTO `master_kokab` VALUES ('105', 'Kabupaten Batang Hari', '7');
INSERT INTO `master_kokab` VALUES ('106', 'Kabupaten Muaro Jambi', '7');
INSERT INTO `master_kokab` VALUES ('107', 'Kabupaten Tanjung Jabung Timur', '7');
INSERT INTO `master_kokab` VALUES ('108', 'Kabupaten Tanjung Jabung Barat', '7');
INSERT INTO `master_kokab` VALUES ('109', 'Kabupaten Tebo', '7');
INSERT INTO `master_kokab` VALUES ('110', 'Kabupaten Bungo', '7');
INSERT INTO `master_kokab` VALUES ('111', 'Kota Jambi', '7');
INSERT INTO `master_kokab` VALUES ('112', 'Kota Sungai Penuh', '7');
INSERT INTO `master_kokab` VALUES ('113', 'Kabupaten Bengkulu Selatan', '8');
INSERT INTO `master_kokab` VALUES ('114', 'Kabupaten Bengkulu Tengah', '8');
INSERT INTO `master_kokab` VALUES ('115', 'Kabupaten Bengkulu Utara', '8');
INSERT INTO `master_kokab` VALUES ('116', 'Kabupaten Kaur', '8');
INSERT INTO `master_kokab` VALUES ('117', 'Kabupaten Kepahiang', '8');
INSERT INTO `master_kokab` VALUES ('118', 'Kabupaten Lebong', '8');
INSERT INTO `master_kokab` VALUES ('119', 'Kabupaten Mukomuko', '8');
INSERT INTO `master_kokab` VALUES ('120', 'Kabupaten Rejang Lebong', '8');
INSERT INTO `master_kokab` VALUES ('121', 'Kabupaten Seluma', '8');
INSERT INTO `master_kokab` VALUES ('122', 'Kota Bengkulu', '8');
INSERT INTO `master_kokab` VALUES ('123', 'Kabupaten Banyuasin', '9');
INSERT INTO `master_kokab` VALUES ('124', 'Kabupaten Empat Lawang', '9');
INSERT INTO `master_kokab` VALUES ('125', 'Kabupaten Lahat', '9');
INSERT INTO `master_kokab` VALUES ('126', 'Kabupaten Muara Enim', '9');
INSERT INTO `master_kokab` VALUES ('127', 'Kabupaten Musi Banyu Asin', '9');
INSERT INTO `master_kokab` VALUES ('128', 'Kabupaten Musi Rawas', '9');
INSERT INTO `master_kokab` VALUES ('129', 'Kabupaten Ogan Ilir', '9');
INSERT INTO `master_kokab` VALUES ('130', 'Kabupaten Ogan Komering Ilir', '9');
INSERT INTO `master_kokab` VALUES ('131', 'Kabupaten Ogan Komering Ulu', '9');
INSERT INTO `master_kokab` VALUES ('132', 'Kabupaten Ogan Komering Ulu Se', '9');
INSERT INTO `master_kokab` VALUES ('133', 'Kabupaten Ogan Komering Ulu Ti', '9');
INSERT INTO `master_kokab` VALUES ('134', 'Kota Lubuklinggau', '9');
INSERT INTO `master_kokab` VALUES ('135', 'Kota Pagar Alam', '9');
INSERT INTO `master_kokab` VALUES ('136', 'Kota Palembang', '9');
INSERT INTO `master_kokab` VALUES ('137', 'Kota Prabumulih', '9');
INSERT INTO `master_kokab` VALUES ('138', 'Kabupaten Lampung Barat', '10');
INSERT INTO `master_kokab` VALUES ('139', 'Kabupaten Lampung Selatan', '10');
INSERT INTO `master_kokab` VALUES ('140', 'Kabupaten Lampung Tengah', '10');
INSERT INTO `master_kokab` VALUES ('141', 'Kabupaten Lampung Timur', '10');
INSERT INTO `master_kokab` VALUES ('142', 'Kabupaten Lampung Utara', '10');
INSERT INTO `master_kokab` VALUES ('143', 'Kabupaten Mesuji', '10');
INSERT INTO `master_kokab` VALUES ('144', 'Kabupaten Pesawaran', '10');
INSERT INTO `master_kokab` VALUES ('145', 'Kabupaten Pringsewu', '10');
INSERT INTO `master_kokab` VALUES ('146', 'Kabupaten Tanggamus', '10');
INSERT INTO `master_kokab` VALUES ('147', 'Kabupaten Tulang Bawang', '10');
INSERT INTO `master_kokab` VALUES ('148', 'Kabupaten Tulang Bawang Barat', '10');
INSERT INTO `master_kokab` VALUES ('149', 'Kabupaten Way Kanan', '10');
INSERT INTO `master_kokab` VALUES ('150', 'Kota Bandar Lampung', '10');
INSERT INTO `master_kokab` VALUES ('151', 'Kota Metro', '10');
INSERT INTO `master_kokab` VALUES ('152', 'Kabupaten Lebak', '11');
INSERT INTO `master_kokab` VALUES ('153', 'Kabupaten Pandeglang', '11');
INSERT INTO `master_kokab` VALUES ('154', 'Kabupaten Serang', '11');
INSERT INTO `master_kokab` VALUES ('155', 'Kabupaten Tangerang', '11');
INSERT INTO `master_kokab` VALUES ('156', 'Kota Cilegon', '11');
INSERT INTO `master_kokab` VALUES ('157', 'Kota Serang', '11');
INSERT INTO `master_kokab` VALUES ('158', 'Kota Tangerang', '11');
INSERT INTO `master_kokab` VALUES ('159', 'Kota Tangerang Selatan', '11');
INSERT INTO `master_kokab` VALUES ('160', 'Kabupaten Adm. Kepulauan Serib', '12');
INSERT INTO `master_kokab` VALUES ('161', 'Kota Jakarta Barat', '12');
INSERT INTO `master_kokab` VALUES ('162', 'Kota Jakarta Pusat', '12');
INSERT INTO `master_kokab` VALUES ('163', 'Kota Jakarta Selatan', '12');
INSERT INTO `master_kokab` VALUES ('164', 'Kota Jakarta Timur', '12');
INSERT INTO `master_kokab` VALUES ('165', 'Kota Jakarta Utara', '12');
INSERT INTO `master_kokab` VALUES ('166', 'Kabupaten Bandung', '13');
INSERT INTO `master_kokab` VALUES ('167', 'Kabupaten Bandung Barat', '13');
INSERT INTO `master_kokab` VALUES ('168', 'Kabupaten Bekasi', '13');
INSERT INTO `master_kokab` VALUES ('169', 'Kabupaten Bogor', '13');
INSERT INTO `master_kokab` VALUES ('170', 'Kabupaten Ciamis', '13');
INSERT INTO `master_kokab` VALUES ('171', 'Kabupaten Cianjur', '13');
INSERT INTO `master_kokab` VALUES ('172', 'Kabupaten Cirebon', '13');
INSERT INTO `master_kokab` VALUES ('173', 'Kabupaten Garut', '13');
INSERT INTO `master_kokab` VALUES ('174', 'Kabupaten Indramayu', '13');
INSERT INTO `master_kokab` VALUES ('175', 'Kabupaten Karawang', '13');
INSERT INTO `master_kokab` VALUES ('176', 'Kabupaten Kuningan', '13');
INSERT INTO `master_kokab` VALUES ('177', 'Kabupaten Majalengka', '13');
INSERT INTO `master_kokab` VALUES ('178', 'Kabupaten Purwakarta', '13');
INSERT INTO `master_kokab` VALUES ('179', 'Kabupaten Subang', '13');
INSERT INTO `master_kokab` VALUES ('180', 'Kabupaten Sukabumi', '13');
INSERT INTO `master_kokab` VALUES ('181', 'Kabupaten Sumedang', '13');
INSERT INTO `master_kokab` VALUES ('182', 'Kabupaten Tasikmalaya', '13');
INSERT INTO `master_kokab` VALUES ('183', 'Kota Bandung', '13');
INSERT INTO `master_kokab` VALUES ('184', 'Kota Banjar', '13');
INSERT INTO `master_kokab` VALUES ('185', 'Kota Bekasi', '13');
INSERT INTO `master_kokab` VALUES ('186', 'Kota Bogor', '13');
INSERT INTO `master_kokab` VALUES ('187', 'Kota Cimahi', '13');
INSERT INTO `master_kokab` VALUES ('188', 'Kota Cirebon', '13');
INSERT INTO `master_kokab` VALUES ('189', 'Kota Depok', '13');
INSERT INTO `master_kokab` VALUES ('190', 'Kota Sukabumi', '13');
INSERT INTO `master_kokab` VALUES ('191', 'Kota Tasikmalaya', '13');
INSERT INTO `master_kokab` VALUES ('192', 'Kabupaten Banjarnegara', '14');
INSERT INTO `master_kokab` VALUES ('193', 'Kabupaten Banyumas', '14');
INSERT INTO `master_kokab` VALUES ('194', 'Kabupaten Batang', '14');
INSERT INTO `master_kokab` VALUES ('195', 'Kabupaten Blora', '14');
INSERT INTO `master_kokab` VALUES ('196', 'Kabupaten Boyolali', '14');
INSERT INTO `master_kokab` VALUES ('197', 'Kabupaten Brebes', '14');
INSERT INTO `master_kokab` VALUES ('198', 'Kabupaten Cilacap', '14');
INSERT INTO `master_kokab` VALUES ('199', 'Kabupaten Demak', '14');
INSERT INTO `master_kokab` VALUES ('200', 'Kabupaten Grobogan', '14');
INSERT INTO `master_kokab` VALUES ('201', 'Kabupaten Jepara', '14');
INSERT INTO `master_kokab` VALUES ('202', 'Kabupaten Karanganyar', '14');
INSERT INTO `master_kokab` VALUES ('203', 'Kabupaten Kebumen', '14');
INSERT INTO `master_kokab` VALUES ('204', 'Kabupaten Kendal', '14');
INSERT INTO `master_kokab` VALUES ('205', 'Kabupaten Klaten', '14');
INSERT INTO `master_kokab` VALUES ('206', 'Kabupaten Kota Tegal', '14');
INSERT INTO `master_kokab` VALUES ('207', 'Kabupaten Kudus', '14');
INSERT INTO `master_kokab` VALUES ('208', 'Kabupaten Magelang', '14');
INSERT INTO `master_kokab` VALUES ('209', 'Kabupaten Pati', '14');
INSERT INTO `master_kokab` VALUES ('210', 'Kabupaten Pekalongan', '14');
INSERT INTO `master_kokab` VALUES ('211', 'Kabupaten Pemalang', '14');
INSERT INTO `master_kokab` VALUES ('212', 'Kabupaten Purbalingga', '14');
INSERT INTO `master_kokab` VALUES ('213', 'Kabupaten Purworejo', '14');
INSERT INTO `master_kokab` VALUES ('214', 'Kabupaten Rembang', '14');
INSERT INTO `master_kokab` VALUES ('215', 'Kabupaten Semarang', '14');
INSERT INTO `master_kokab` VALUES ('216', 'Kabupaten Sragen', '14');
INSERT INTO `master_kokab` VALUES ('217', 'Kabupaten Sukoharjo', '14');
INSERT INTO `master_kokab` VALUES ('218', 'Kabupaten Temanggung', '14');
INSERT INTO `master_kokab` VALUES ('219', 'Kabupaten Wonogiri', '14');
INSERT INTO `master_kokab` VALUES ('220', 'Kabupaten Wonosobo', '14');
INSERT INTO `master_kokab` VALUES ('221', 'Kota Magelang', '14');
INSERT INTO `master_kokab` VALUES ('222', 'Kota Pekalongan', '14');
INSERT INTO `master_kokab` VALUES ('223', 'Kota Salatiga', '14');
INSERT INTO `master_kokab` VALUES ('224', 'Kota Semarang', '14');
INSERT INTO `master_kokab` VALUES ('225', 'Kota Surakarta', '14');
INSERT INTO `master_kokab` VALUES ('226', 'Kota Tegal', '14');
INSERT INTO `master_kokab` VALUES ('227', 'Kabupaten Bantul', '15');
INSERT INTO `master_kokab` VALUES ('228', 'Kabupaten Gunung Kidul', '15');
INSERT INTO `master_kokab` VALUES ('229', 'Kabupaten Kulon Progo', '15');
INSERT INTO `master_kokab` VALUES ('230', 'Kabupaten Sleman', '15');
INSERT INTO `master_kokab` VALUES ('231', 'Kota Yogyakarta', '15');
INSERT INTO `master_kokab` VALUES ('232', 'Kabupaten Bangkalan', '16');
INSERT INTO `master_kokab` VALUES ('233', 'Kabupaten Banyuwangi', '16');
INSERT INTO `master_kokab` VALUES ('234', 'Kabupaten Blitar', '16');
INSERT INTO `master_kokab` VALUES ('235', 'Kabupaten Bojonegoro', '16');
INSERT INTO `master_kokab` VALUES ('236', 'Kabupaten Bondowoso', '16');
INSERT INTO `master_kokab` VALUES ('237', 'Kabupaten Gresik', '16');
INSERT INTO `master_kokab` VALUES ('238', 'Kabupaten Jember', '16');
INSERT INTO `master_kokab` VALUES ('239', 'Kabupaten Jombang', '16');
INSERT INTO `master_kokab` VALUES ('240', 'Kabupaten Kediri', '16');
INSERT INTO `master_kokab` VALUES ('241', 'Kabupaten Lamongan', '16');
INSERT INTO `master_kokab` VALUES ('242', 'Kabupaten Lumajang', '16');
INSERT INTO `master_kokab` VALUES ('243', 'Kabupaten Madiun', '16');
INSERT INTO `master_kokab` VALUES ('244', 'Kabupaten Magetan', '16');
INSERT INTO `master_kokab` VALUES ('245', 'Kabupaten Malang', '16');
INSERT INTO `master_kokab` VALUES ('246', 'Kabupaten Mojokerto', '16');
INSERT INTO `master_kokab` VALUES ('247', 'Kabupaten Nganjuk', '16');
INSERT INTO `master_kokab` VALUES ('248', 'Kabupaten Ngawi', '16');
INSERT INTO `master_kokab` VALUES ('249', 'Kabupaten Pacitan', '16');
INSERT INTO `master_kokab` VALUES ('250', 'Kabupaten Pamekasan', '16');
INSERT INTO `master_kokab` VALUES ('251', 'Kabupaten Pasuruan', '16');
INSERT INTO `master_kokab` VALUES ('252', 'Kabupaten Ponorogo', '16');
INSERT INTO `master_kokab` VALUES ('253', 'Kabupaten Probolinggo', '16');
INSERT INTO `master_kokab` VALUES ('254', 'Kabupaten Sampang', '16');
INSERT INTO `master_kokab` VALUES ('255', 'Kabupaten Sidoarjo', '16');
INSERT INTO `master_kokab` VALUES ('256', 'Kabupaten Situbondo', '16');
INSERT INTO `master_kokab` VALUES ('257', 'Kabupaten Sumenep', '16');
INSERT INTO `master_kokab` VALUES ('258', 'Kabupaten Trenggalek', '16');
INSERT INTO `master_kokab` VALUES ('259', 'Kabupaten Tuban', '16');
INSERT INTO `master_kokab` VALUES ('260', 'Kabupaten Tulungagung', '16');
INSERT INTO `master_kokab` VALUES ('261', 'Kota Batu', '16');
INSERT INTO `master_kokab` VALUES ('262', 'Kota Blitar', '16');
INSERT INTO `master_kokab` VALUES ('263', 'Kota Kediri', '16');
INSERT INTO `master_kokab` VALUES ('264', 'Kota Madiun', '16');
INSERT INTO `master_kokab` VALUES ('265', 'Kota Malang', '16');
INSERT INTO `master_kokab` VALUES ('266', 'Kota Mojokerto', '16');
INSERT INTO `master_kokab` VALUES ('267', 'Kota Pasuruan', '16');
INSERT INTO `master_kokab` VALUES ('268', 'Kota Probolinggo', '16');
INSERT INTO `master_kokab` VALUES ('269', 'Kota Surabaya', '16');
INSERT INTO `master_kokab` VALUES ('270', 'Kabupaten Badung', '17');
INSERT INTO `master_kokab` VALUES ('271', 'Kabupaten Bangli', '17');
INSERT INTO `master_kokab` VALUES ('272', 'Kabupaten Buleleng', '17');
INSERT INTO `master_kokab` VALUES ('273', 'Kabupaten Gianyar', '17');
INSERT INTO `master_kokab` VALUES ('274', 'Kabupaten Jembrana', '17');
INSERT INTO `master_kokab` VALUES ('275', 'Kabupaten Karang Asem', '17');
INSERT INTO `master_kokab` VALUES ('276', 'Kabupaten Klungkung', '17');
INSERT INTO `master_kokab` VALUES ('277', 'Kabupaten Tabanan', '17');
INSERT INTO `master_kokab` VALUES ('278', 'Kota Denpasar', '17');
INSERT INTO `master_kokab` VALUES ('279', 'Kabupaten Bima', '18');
INSERT INTO `master_kokab` VALUES ('280', 'Kabupaten Dompu', '18');
INSERT INTO `master_kokab` VALUES ('281', 'Kabupaten Lombok Barat', '18');
INSERT INTO `master_kokab` VALUES ('282', 'Kabupaten Lombok Tengah', '18');
INSERT INTO `master_kokab` VALUES ('283', 'Kabupaten Lombok Timur', '18');
INSERT INTO `master_kokab` VALUES ('284', 'Kabupaten Lombok Utara', '18');
INSERT INTO `master_kokab` VALUES ('285', 'Kabupaten Sumbawa', '18');
INSERT INTO `master_kokab` VALUES ('286', 'Kabupaten Sumbawa Barat', '18');
INSERT INTO `master_kokab` VALUES ('287', 'Kota Bima', '18');
INSERT INTO `master_kokab` VALUES ('288', 'Kota Mataram', '18');
INSERT INTO `master_kokab` VALUES ('289', 'Kabupaten Alor', '19');
INSERT INTO `master_kokab` VALUES ('290', 'Kabupaten Belu', '19');
INSERT INTO `master_kokab` VALUES ('291', 'Kabupaten Ende', '19');
INSERT INTO `master_kokab` VALUES ('292', 'Kabupaten Flores Timur', '19');
INSERT INTO `master_kokab` VALUES ('293', 'Kabupaten Kupang', '19');
INSERT INTO `master_kokab` VALUES ('294', 'Kabupaten Lembata', '19');
INSERT INTO `master_kokab` VALUES ('295', 'Kabupaten Manggarai', '19');
INSERT INTO `master_kokab` VALUES ('296', 'Kabupaten Manggarai Barat', '19');
INSERT INTO `master_kokab` VALUES ('297', 'Kabupaten Manggarai Timur', '19');
INSERT INTO `master_kokab` VALUES ('298', 'Kabupaten Nagekeo', '19');
INSERT INTO `master_kokab` VALUES ('299', 'Kabupaten Ngada', '19');
INSERT INTO `master_kokab` VALUES ('300', 'Kabupaten Rote Ndao', '19');
INSERT INTO `master_kokab` VALUES ('301', 'Kabupaten Sabu Raijua', '19');
INSERT INTO `master_kokab` VALUES ('302', 'Kabupaten Sikka', '19');
INSERT INTO `master_kokab` VALUES ('303', 'Kabupaten Sumba Barat', '19');
INSERT INTO `master_kokab` VALUES ('304', 'Kabupaten Sumba Barat Daya', '19');
INSERT INTO `master_kokab` VALUES ('305', 'Kabupaten Sumba Tengah', '19');
INSERT INTO `master_kokab` VALUES ('306', 'Kabupaten Sumba Timur', '19');
INSERT INTO `master_kokab` VALUES ('307', 'Kabupaten Timor Tengah Selatan', '19');
INSERT INTO `master_kokab` VALUES ('308', 'Kabupaten Timor Tengah Utara', '19');
INSERT INTO `master_kokab` VALUES ('309', 'Kota Kupang', '19');
INSERT INTO `master_kokab` VALUES ('310', 'Kabupaten Bengkayang', '20');
INSERT INTO `master_kokab` VALUES ('311', 'Kabupaten Kapuas Hulu', '20');
INSERT INTO `master_kokab` VALUES ('312', 'Kabupaten Kayong Utara', '20');
INSERT INTO `master_kokab` VALUES ('313', 'Kabupaten Ketapang', '20');
INSERT INTO `master_kokab` VALUES ('314', 'Kabupaten Kubu Raya', '20');
INSERT INTO `master_kokab` VALUES ('315', 'Kabupaten Landak', '20');
INSERT INTO `master_kokab` VALUES ('316', 'Kabupaten Melawi', '20');
INSERT INTO `master_kokab` VALUES ('317', 'Kabupaten Pontianak', '20');
INSERT INTO `master_kokab` VALUES ('318', 'Kabupaten Sambas', '20');
INSERT INTO `master_kokab` VALUES ('319', 'Kabupaten Sanggau', '20');
INSERT INTO `master_kokab` VALUES ('320', 'Kabupaten Sekadau', '20');
INSERT INTO `master_kokab` VALUES ('321', 'Kabupaten Sintang', '20');
INSERT INTO `master_kokab` VALUES ('322', 'Kota Pontianak', '20');
INSERT INTO `master_kokab` VALUES ('323', 'Kota Singkawang', '20');
INSERT INTO `master_kokab` VALUES ('324', 'Kabupaten Barito Selatan', '21');
INSERT INTO `master_kokab` VALUES ('325', 'Kabupaten Barito Timur', '21');
INSERT INTO `master_kokab` VALUES ('326', 'Kabupaten Barito Utara', '21');
INSERT INTO `master_kokab` VALUES ('327', 'Kabupaten Gunung Mas', '21');
INSERT INTO `master_kokab` VALUES ('328', 'Kabupaten Kapuas', '21');
INSERT INTO `master_kokab` VALUES ('329', 'Kabupaten Katingan', '21');
INSERT INTO `master_kokab` VALUES ('330', 'Kabupaten Kotawaringin Barat', '21');
INSERT INTO `master_kokab` VALUES ('331', 'Kabupaten Kotawaringin Timur', '21');
INSERT INTO `master_kokab` VALUES ('332', 'Kabupaten Lamandau', '21');
INSERT INTO `master_kokab` VALUES ('333', 'Kabupaten Murung Raya', '21');
INSERT INTO `master_kokab` VALUES ('334', 'Kabupaten Pulang Pisau', '21');
INSERT INTO `master_kokab` VALUES ('335', 'Kabupaten Seruyan', '21');
INSERT INTO `master_kokab` VALUES ('336', 'Kabupaten Sukamara', '21');
INSERT INTO `master_kokab` VALUES ('337', 'Kota Palangkaraya', '21');
INSERT INTO `master_kokab` VALUES ('338', 'Kabupaten Balangan', '22');
INSERT INTO `master_kokab` VALUES ('339', 'Kabupaten Banjar', '22');
INSERT INTO `master_kokab` VALUES ('340', 'Kabupaten Barito Kuala', '22');
INSERT INTO `master_kokab` VALUES ('341', 'Kabupaten Hulu Sungai Selatan', '22');
INSERT INTO `master_kokab` VALUES ('342', 'Kabupaten Hulu Sungai Tengah', '22');
INSERT INTO `master_kokab` VALUES ('343', 'Kabupaten Hulu Sungai Utara', '22');
INSERT INTO `master_kokab` VALUES ('344', 'Kabupaten Kota Baru', '22');
INSERT INTO `master_kokab` VALUES ('345', 'Kabupaten Tabalong', '22');
INSERT INTO `master_kokab` VALUES ('346', 'Kabupaten Tanah Bumbu', '22');
INSERT INTO `master_kokab` VALUES ('347', 'Kabupaten Tanah Laut', '22');
INSERT INTO `master_kokab` VALUES ('348', 'Kabupaten Tapin', '22');
INSERT INTO `master_kokab` VALUES ('349', 'Kota Banjar Baru', '22');
INSERT INTO `master_kokab` VALUES ('350', 'Kota Banjarmasin', '22');
INSERT INTO `master_kokab` VALUES ('351', 'Kabupaten Berau', '23');
INSERT INTO `master_kokab` VALUES ('352', 'Kabupaten Bulongan', '23');
INSERT INTO `master_kokab` VALUES ('353', 'Kabupaten Kutai Barat', '23');
INSERT INTO `master_kokab` VALUES ('354', 'Kabupaten Kutai Kartanegara', '23');
INSERT INTO `master_kokab` VALUES ('355', 'Kabupaten Kutai Timur', '23');
INSERT INTO `master_kokab` VALUES ('356', 'Kabupaten Malinau', '23');
INSERT INTO `master_kokab` VALUES ('357', 'Kabupaten Nunukan', '23');
INSERT INTO `master_kokab` VALUES ('358', 'Kabupaten Paser', '23');
INSERT INTO `master_kokab` VALUES ('359', 'Kabupaten Penajam Paser Utara', '23');
INSERT INTO `master_kokab` VALUES ('360', 'Kabupaten Tana Tidung', '23');
INSERT INTO `master_kokab` VALUES ('361', 'Kota Balikpapan', '23');
INSERT INTO `master_kokab` VALUES ('362', 'Kota Bontang', '23');
INSERT INTO `master_kokab` VALUES ('363', 'Kota Samarinda', '23');
INSERT INTO `master_kokab` VALUES ('364', 'Kota Tarakan', '23');
INSERT INTO `master_kokab` VALUES ('365', 'Kabupaten Boalemo', '24');
INSERT INTO `master_kokab` VALUES ('366', 'Kabupaten Bone Bolango', '24');
INSERT INTO `master_kokab` VALUES ('367', 'Kabupaten Gorontalo', '24');
INSERT INTO `master_kokab` VALUES ('368', 'Kabupaten Gorontalo Utara', '24');
INSERT INTO `master_kokab` VALUES ('369', 'Kabupaten Pohuwato', '24');
INSERT INTO `master_kokab` VALUES ('370', 'Kota Gorontalo', '24');
INSERT INTO `master_kokab` VALUES ('371', 'Kabupaten Bantaeng', '25');
INSERT INTO `master_kokab` VALUES ('372', 'Kabupaten Barru', '25');
INSERT INTO `master_kokab` VALUES ('373', 'Kabupaten Bone', '25');
INSERT INTO `master_kokab` VALUES ('374', 'Kabupaten Bulukumba', '25');
INSERT INTO `master_kokab` VALUES ('375', 'Kabupaten Enrekang', '25');
INSERT INTO `master_kokab` VALUES ('376', 'Kabupaten Gowa', '25');
INSERT INTO `master_kokab` VALUES ('377', 'Kabupaten Jeneponto', '25');
INSERT INTO `master_kokab` VALUES ('378', 'Kabupaten Luwu', '25');
INSERT INTO `master_kokab` VALUES ('379', 'Kabupaten Luwu Timur', '25');
INSERT INTO `master_kokab` VALUES ('380', 'Kabupaten Luwu Utara', '25');
INSERT INTO `master_kokab` VALUES ('381', 'Kabupaten Maros', '25');
INSERT INTO `master_kokab` VALUES ('382', 'Kabupaten Pangkajene Kepulauan', '25');
INSERT INTO `master_kokab` VALUES ('383', 'Kabupaten Pinrang', '25');
INSERT INTO `master_kokab` VALUES ('384', 'Kabupaten Selayar', '25');
INSERT INTO `master_kokab` VALUES ('385', 'Kabupaten Sidenreng Rappang', '25');
INSERT INTO `master_kokab` VALUES ('386', 'Kabupaten Sinjai', '25');
INSERT INTO `master_kokab` VALUES ('387', 'Kabupaten Soppeng', '25');
INSERT INTO `master_kokab` VALUES ('388', 'Kabupaten Takalar', '25');
INSERT INTO `master_kokab` VALUES ('389', 'Kabupaten Tana Toraja', '25');
INSERT INTO `master_kokab` VALUES ('390', 'Kabupaten Toraja Utara', '25');
INSERT INTO `master_kokab` VALUES ('391', 'Kabupaten Wajo', '25');
INSERT INTO `master_kokab` VALUES ('392', 'Kota Makassar', '25');
INSERT INTO `master_kokab` VALUES ('393', 'Kota Palopo', '25');
INSERT INTO `master_kokab` VALUES ('394', 'Kota Pare-pare', '25');
INSERT INTO `master_kokab` VALUES ('395', 'Kabupaten Bombana', '26');
INSERT INTO `master_kokab` VALUES ('396', 'Kabupaten Buton', '26');
INSERT INTO `master_kokab` VALUES ('397', 'Kabupaten Buton Utara', '26');
INSERT INTO `master_kokab` VALUES ('398', 'Kabupaten Kolaka', '26');
INSERT INTO `master_kokab` VALUES ('399', 'Kabupaten Kolaka Utara', '26');
INSERT INTO `master_kokab` VALUES ('400', 'Kabupaten Konawe', '26');
INSERT INTO `master_kokab` VALUES ('401', 'Kabupaten Konawe Selatan', '26');
INSERT INTO `master_kokab` VALUES ('402', 'Kabupaten Konawe Utara', '26');
INSERT INTO `master_kokab` VALUES ('403', 'Kabupaten Muna', '26');
INSERT INTO `master_kokab` VALUES ('404', 'Kabupaten Wakatobi', '26');
INSERT INTO `master_kokab` VALUES ('405', 'Kota Bau-bau', '26');
INSERT INTO `master_kokab` VALUES ('406', 'Kota Kendari', '26');
INSERT INTO `master_kokab` VALUES ('407', 'Kabupaten Banggai', '27');
INSERT INTO `master_kokab` VALUES ('408', 'Kabupaten Banggai Kepulauan', '27');
INSERT INTO `master_kokab` VALUES ('409', 'Kabupaten Buol', '27');
INSERT INTO `master_kokab` VALUES ('410', 'Kabupaten Donggala', '27');
INSERT INTO `master_kokab` VALUES ('411', 'Kabupaten Morowali', '27');
INSERT INTO `master_kokab` VALUES ('412', 'Kabupaten Parigi Moutong', '27');
INSERT INTO `master_kokab` VALUES ('413', 'Kabupaten Poso', '27');
INSERT INTO `master_kokab` VALUES ('414', 'Kabupaten Sigi', '27');
INSERT INTO `master_kokab` VALUES ('415', 'Kabupaten Tojo Una-Una', '27');
INSERT INTO `master_kokab` VALUES ('416', 'Kabupaten Toli Toli', '27');
INSERT INTO `master_kokab` VALUES ('417', 'Kota Palu', '27');
INSERT INTO `master_kokab` VALUES ('418', 'Kabupaten Bolaang Mangondow', '28');
INSERT INTO `master_kokab` VALUES ('419', 'Kabupaten Bolaang Mangondow Se', '28');
INSERT INTO `master_kokab` VALUES ('420', 'Kabupaten Bolaang Mangondow Ti', '28');
INSERT INTO `master_kokab` VALUES ('421', 'Kabupaten Bolaang Mangondow Ut', '28');
INSERT INTO `master_kokab` VALUES ('422', 'Kabupaten Kepulauan Sangihe', '28');
INSERT INTO `master_kokab` VALUES ('423', 'Kabupaten Kepulauan Siau Tagul', '28');
INSERT INTO `master_kokab` VALUES ('424', 'Kabupaten Kepulauan Talaud', '28');
INSERT INTO `master_kokab` VALUES ('425', 'Kabupaten Minahasa', '28');
INSERT INTO `master_kokab` VALUES ('426', 'Kabupaten Minahasa Selatan', '28');
INSERT INTO `master_kokab` VALUES ('427', 'Kabupaten Minahasa Tenggara', '28');
INSERT INTO `master_kokab` VALUES ('428', 'Kabupaten Minahasa Utara', '28');
INSERT INTO `master_kokab` VALUES ('429', 'Kota Bitung', '28');
INSERT INTO `master_kokab` VALUES ('430', 'Kota Kotamobagu', '28');
INSERT INTO `master_kokab` VALUES ('431', 'Kota Manado', '28');
INSERT INTO `master_kokab` VALUES ('432', 'Kota Tomohon', '28');
INSERT INTO `master_kokab` VALUES ('433', 'Kabupaten Majene', '29');
INSERT INTO `master_kokab` VALUES ('434', 'Kabupaten Mamasa', '29');
INSERT INTO `master_kokab` VALUES ('435', 'Kabupaten Mamuju', '29');
INSERT INTO `master_kokab` VALUES ('436', 'Kabupaten Mamuju Utara', '29');
INSERT INTO `master_kokab` VALUES ('437', 'Kabupaten Polewali Mandar', '29');
INSERT INTO `master_kokab` VALUES ('438', 'Kabupaten Buru', '30');
INSERT INTO `master_kokab` VALUES ('439', 'Kabupaten Buru Selatan', '30');
INSERT INTO `master_kokab` VALUES ('440', 'Kabupaten Kepulauan Aru', '30');
INSERT INTO `master_kokab` VALUES ('441', 'Kabupaten Maluku Barat Daya', '30');
INSERT INTO `master_kokab` VALUES ('442', 'Kabupaten Maluku Tengah', '30');
INSERT INTO `master_kokab` VALUES ('443', 'Kabupaten Maluku Tenggara', '30');
INSERT INTO `master_kokab` VALUES ('444', 'Kabupaten Maluku Tenggara Bara', '30');
INSERT INTO `master_kokab` VALUES ('445', 'Kabupaten Seram Bagian Barat', '30');
INSERT INTO `master_kokab` VALUES ('446', 'Kabupaten Seram Bagian Timur', '30');
INSERT INTO `master_kokab` VALUES ('447', 'Kota Ambon', '30');
INSERT INTO `master_kokab` VALUES ('448', 'Kota Tual', '30');
INSERT INTO `master_kokab` VALUES ('449', 'Kabupaten Halmahera Barat', '31');
INSERT INTO `master_kokab` VALUES ('450', 'Kabupaten Halmahera Selatan', '31');
INSERT INTO `master_kokab` VALUES ('451', 'Kabupaten Halmahera Tengah', '31');
INSERT INTO `master_kokab` VALUES ('452', 'Kabupaten Halmahera Timur', '31');
INSERT INTO `master_kokab` VALUES ('453', 'Kabupaten Halmahera Utara', '31');
INSERT INTO `master_kokab` VALUES ('454', 'Kabupaten Kepulauan Sula', '31');
INSERT INTO `master_kokab` VALUES ('455', 'Kabupaten Pulau Morotai', '31');
INSERT INTO `master_kokab` VALUES ('456', 'Kota Ternate', '31');
INSERT INTO `master_kokab` VALUES ('457', 'Kota Tidore Kepulauan', '31');
INSERT INTO `master_kokab` VALUES ('458', 'Kabupaten Fakfak', '32');
INSERT INTO `master_kokab` VALUES ('459', 'Kabupaten Kaimana', '32');
INSERT INTO `master_kokab` VALUES ('460', 'Kabupaten Manokwari', '32');
INSERT INTO `master_kokab` VALUES ('461', 'Kabupaten Maybrat', '32');
INSERT INTO `master_kokab` VALUES ('462', 'Kabupaten Raja Ampat', '32');
INSERT INTO `master_kokab` VALUES ('463', 'Kabupaten Sorong', '32');
INSERT INTO `master_kokab` VALUES ('464', 'Kabupaten Sorong Selatan', '32');
INSERT INTO `master_kokab` VALUES ('465', 'Kabupaten Tambrauw', '32');
INSERT INTO `master_kokab` VALUES ('466', 'Kabupaten Teluk Bintuni', '32');
INSERT INTO `master_kokab` VALUES ('467', 'Kabupaten Teluk Wondama', '32');
INSERT INTO `master_kokab` VALUES ('468', 'Kota Sorong', '32');
INSERT INTO `master_kokab` VALUES ('469', 'Kabupaten Merauke', '33');
INSERT INTO `master_kokab` VALUES ('470', 'Kabupaten Jayawijaya', '33');
INSERT INTO `master_kokab` VALUES ('471', 'Kabupaten Nabire', '33');
INSERT INTO `master_kokab` VALUES ('472', 'Kabupaten Kepulauan Yapen', '33');
INSERT INTO `master_kokab` VALUES ('473', 'Kabupaten Biak Numfor', '33');
INSERT INTO `master_kokab` VALUES ('474', 'Kabupaten Paniai', '33');
INSERT INTO `master_kokab` VALUES ('475', 'Kabupaten Puncak Jaya', '33');
INSERT INTO `master_kokab` VALUES ('476', 'Kabupaten Mimika', '33');
INSERT INTO `master_kokab` VALUES ('477', 'Kabupaten Boven Digoel', '33');
INSERT INTO `master_kokab` VALUES ('478', 'Kabupaten Mappi', '33');
INSERT INTO `master_kokab` VALUES ('479', 'Kabupaten Asmat', '33');
INSERT INTO `master_kokab` VALUES ('480', 'Kabupaten Yahukimo', '33');
INSERT INTO `master_kokab` VALUES ('481', 'Kabupaten Pegunungan Bintang', '33');
INSERT INTO `master_kokab` VALUES ('482', 'Kabupaten Tolikara', '33');
INSERT INTO `master_kokab` VALUES ('483', 'Kabupaten Sarmi', '33');
INSERT INTO `master_kokab` VALUES ('484', 'Kabupaten Keerom', '33');
INSERT INTO `master_kokab` VALUES ('485', 'Kabupaten Waropen', '33');
INSERT INTO `master_kokab` VALUES ('486', 'Kabupaten Jayapura', '33');
INSERT INTO `master_kokab` VALUES ('487', 'Kabupaten Deiyai', '33');
INSERT INTO `master_kokab` VALUES ('488', 'Kabupaten Dogiyai', '33');
INSERT INTO `master_kokab` VALUES ('489', 'Kabupaten Intan Jaya', '33');
INSERT INTO `master_kokab` VALUES ('490', 'Kabupaten Lanny Jaya', '33');
INSERT INTO `master_kokab` VALUES ('491', 'Kabupaten Mamberamo Raya', '33');
INSERT INTO `master_kokab` VALUES ('492', 'Kabupaten Mamberamo Tengah', '33');
INSERT INTO `master_kokab` VALUES ('493', 'Kabupaten Nduga', '33');
INSERT INTO `master_kokab` VALUES ('494', 'Kabupaten Puncak', '33');
INSERT INTO `master_kokab` VALUES ('495', 'Kabupaten Supiori', '33');
INSERT INTO `master_kokab` VALUES ('496', 'Kabupaten Yalimo', '33');
INSERT INTO `master_kokab` VALUES ('497', 'Kota Jayapura', '33');
INSERT INTO `master_kokab` VALUES ('498', 'Kabupaten Bulungan', '34');
INSERT INTO `master_kokab` VALUES ('499', 'Kabupaten Malinau', '34');
INSERT INTO `master_kokab` VALUES ('500', 'Kabupaten Nunukan', '34');
INSERT INTO `master_kokab` VALUES ('501', 'Kabupaten Tana Tidung', '34');
INSERT INTO `master_kokab` VALUES ('502', 'Kota Tarakan', '34');
